batch_size: 256
eval_batch_size: 256
dropout: 0.0
lr: 0.0005
num_epochs: 30
num_layers: 5
JK : "none"
task_names:
  - "arxiv_fs"
  - "FB15K237_fs"
  - "mol_fs"
d_multiple:
  - 1
  - 1
  - 1
d_min_ratio:
  - 1
  - 1
  - 1
exp_name: "OFA_soft_and_hard_"
reload_freq: 0
limit_val_batches: 0 
checkpoint_interval: 10
fs_sample_size: 60000